[package]
name = "parsing"
version = "0.2.0"
authors = ["xialu <evan_l00@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
